---
kind: pipeline
type: kubernetes
name: callisto-timecard-restapi

platform:
  os: linux
  arch: amd64

steps:
  - name: lint_dockerfile
    pull: if-not-exists
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile
    when:
      event:
        - push
        - pull_request