---
kind: pipeline
type: kubernetes
name: lint-files

platform:
  os: linux
  arch: amd64

trigger:
  event:
    include:
    - push
    - pull_request
    exclude:
    - promote

steps:
  - name: lint_dockerfiles
    pull: if-not-exists
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint Dockerfile
      - hadolint db/Dockerfile

  - name: lint_helm_files
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: ./helm
      values_files:
        - ./helm/values/dev-values.yaml
        - ./helm/values/test-values.yaml

---
kind: pipeline
type: kubernetes
name: callisto-timecard-restapi-build

platform:
  os: linux
  arch: amd64

depends_on:
  - lint-files

trigger:
  event:
    exclude:
      - promote

steps:
  - name: fetch
    image: alpine/git
    commands:
      - "git fetch origin +refs/heads/main:"

  - name: build
    image: maven:3.8.3-openjdk-17
    environment:
      ARTIFACTORY_TOKEN:
        from_secret: artifactory_token
    commands:
      - mvn -s ./timecard_settings.xml clean verify

  - name: sonar
    image: maven:3.8.3-openjdk-17
    depends_on:
      - build
    environment:
      ARTIFACTORY_TOKEN:
        from_secret: artifactory_token
      SONAR_HOST:
        from_secret: sonar_cloud_host
      SONAR_TOKEN:
        from_secret: sonar_cloud_token
    commands:
      - mvn -s ./timecard_settings.xml sonar:sonar 
        -Dsonar.host.url=$${SONAR_HOST} 
        -Dsonar.login=$${SONAR_TOKEN} 
        -Dsonar.organization=ukhomeoffice 
        -Dsonar.projectKey=callisto-timecard-restapi 
        -Dsonar.branch.name=$DRONE_BRANCH 
        -Dsonar.projectName=callisto-timecard-restapi 
        -Dsonar.qualitygate.wait=true
    when:
      event:
        exclude:
          - pull_request


  - name: build_tag_push_ecr
    pull: if-not-exists
    image: plugins/ecr
    depends_on:
      - sonar
    environment:
      AWS_REGION: eu-west-2
    settings:
      access_key:
        from_secret: ecr_timecard_restapi_access_key_id
      secret_key:
        from_secret: ecr_timecard_restapi_secret_access_key
      repo: callisto/timecard-restapi
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      tags:
      - latest
      - ${DRONE_COMMIT_SHA}
    when:
      event:
        - push
      branch:
        - main

---
kind: pipeline
type: kubernetes
name: callisto-timecard-database-schema

platform:
  os: linux
  arch: amd64

depends_on:
  - lint-files

trigger:
  event:
    exclude:
      - promote

steps:
  - name: build_tag_push_ecr
    pull: if-not-exists
    image: plugins/ecr
    environment:
      AWS_REGION: eu-west-2
    settings:
      access_key:
        from_secret: ecr_timecard_database_access_key_id
      secret_key:
        from_secret: ecr_timecard_database_secret_access_key
      repo: callisto/timecard-database
      dockerfile: db/Dockerfile
      context: db
      registry: 340268328991.dkr.ecr.eu-west-2.amazonaws.com
      tags:
        - latest
        - ${DRONE_COMMIT_SHA}
    when:
      event:
        - push
      branch:
        - main

---
kind: pipeline
type: kubernetes
name: callisto-timecard-restapi-dev-deploy

platform:
  os: linux
  arch: amd64

depends_on:
  - callisto-timecard-restapi-build
  - callisto-timecard-database-schema

trigger:
  event:
    include:
      - push
    exclude:
      - promote
  branch:
#    - main
    - task/eahw-2428/manual-promote-to-prod-pipeline #temporarily use current branch for testing

steps:
  - name: deploy_to_dev
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-dev
      mode: upgrade
      chart: ./helm
      values:
        - image.tag=${DRONE_COMMIT_SHA}
      values_files:
        - ./helm/values/dev-values.yaml
      release: callisto-timecard-restapi
      kube_certificate:
        from_secret: notprod_kube_api_certificate
      kube_api_server:
        from_secret: not_prod_kube_api_url
      kube_token:
        from_secret: dev_kube_token

---
kind: pipeline
type: kubernetes
name: callisto-timecard-restapi-test-deploy

platform:
  os: linux
  arch: amd64

depends_on:
  - callisto-timecard-restapi-dev-deploy

trigger:
  event:
    - push
  exclude:
    - promote
  branch:
    - main
  #    - task/eahw-2428/manual-promote-to-prod-pipeline #temporarily use current branch for testing

steps:
  - name: deploy_to_test
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-test
      mode: upgrade
      chart: ./helm
      values:
        - image.tag=${DRONE_COMMIT_SHA}
      values_files:
        - ./helm/values/test-values.yaml
      release: callisto-timecard-restapi
      kube_certificate:
        from_secret: notprod_kube_api_certificate
      kube_api_server:
        from_secret: not_prod_kube_api_url
      kube_token:
        from_secret: test_kube_token


---
kind: pipeline
type: kubernetes
name: callisto-timecard-restapi-prod-deploy

platform:
  os: linux
  arch: amd64

depends_on:
  - callisto-timecard-restapi-test-deploy

trigger:
  event:
    - promote
  target:
    - production

steps:
  - name: deploy_to_prod_check
    image: alpine:latest
    commands:
      - echo Cannot promote from non 'main' branch
      - exit 1
    when:
      branch:
        exclude:
          - main

  - name: deploy_to_prod
    image: pelotech/drone-helm3
    settings:
      namespace: callisto-prod
      mode: upgrade
      chart: ./helm
      values:
        - image.tag=latest #tempoarily using latest for testing, use commit sha before creating PR
      values_files:
        - ./helm/values/prod-values.yaml
      release: callisto-timecard-restapi
      kube_certificate:
        from_secret: prod_kube_api_certificate
      kube_api_server:
        from_secret: prod_kube_api_url
      kube_token:
        from_secret: prod_kube_token
      when:
        event:
          - push
        branch:
          - main


---
kind: pipeline
type: kubernetes
name: build notifications

trigger:
  status:
    - success
    - failure

depends_on:
  - callisto-timecard-restapi-build
  - callisto-timecard-restapi-dev-deploy
  - callisto-timecard-restapi-test-deploy
  - callisto-timecard-restapi-prod-deploy

slack: &slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
      channel: callisto-tech-notifications
      username: Drone

steps:
  - name: slack_build
    <<: *slack
    settings:
      template: |
        {{#success build.status}}
          Build #{{ build.number }} succeeded! :tada:
        {{else}}
          Build #{{ build.number }} failed :alert:
        {{/success}}
        Commit: <${DRONE_REPO_LINK}/commit/{{ build.commit }}|{{ truncate build.commit 8 }}> - {{{ trim build.message }}}
        Repo: {{ repo.name }}
        Branch: <${DRONE_REPO_LINK}/commits/{{ build.branch }}|{{ build.branch }}>
        Author: {{ build.author }}
        <https://sonarcloud.io/dashboard?id=callisto-timecard-restapi&branch={{ build.branch }}&resolved=false|SonarCloud Analysis Report>
    when:
      event:
        - push

  - name: slack_deploy
    <<: *slack
    settings:
      template: >
        {{#success build.status}}
          :rocket: Successful *{{uppercasefirst build.deployTo}}* deployment for *{{repo.name}} build #{{build.number}}*.          
        {{else}}
          :zombie: Problem *{{uppercasefirst build.deployTo}}* deployment failed for *{{repo.name}} <${DRONE_BUILD_LINK}| build #{{build.number}}*>.
        {{/success}}
    when:
      event:
        - promote
      target:
        - production

  - name: slack_deploy_non_prod_promotion
    <<: *slack
    settings:
      template: >
        :zombie: Problem *{{uppercasefirst build.deployTo}}* deployment failed for *{{repo.name}} <${DRONE_BUILD_LINK}| build #{{build.number}}*>.
    when:
      event:
        - promote
      target:
        exclude:
          - production