version: '3.3'

x-db-settings: &db-settings
  pull_policy: always
  environment:
    - DATABASE_NAME=callisto
    - DATABASE_USERNAME=dev
    - DATABASE_PASSWORD=dev
    - DATABASE_ENDPOINT=postgres
    - DATABASE_PORT=5432
  networks:
    - callisto

x-liquibase-settings: &liquibase-setting
  pull_policy: always
  command:
    - "--url=jdbc:postgresql://postgres:5432/callisto"
    - "--username=dev"
    - "--password=dev"
    - "--changeLogFile=changelog/db.changelog-main.yml"
    - "update"
  networks:
    - callisto

services:
  timecard-restapi:
    <<: *db-settings
    build:
      context: ./
      dockerfile: dev.dockerfile
    volumes:
      - ./:/app
      - $HOME/.m2:/root/.m2 # required for jparest dependencies (artifactory)
    working_dir: /app
    command: sh run.sh
    ports:
      - 50000:9090
      - 35729:35729
      - 5005:5005

    depends_on:
      - timecard-database-migrations

  timecard-database-migrations:
    <<: *liquibase-setting
    image: "340268328991.dkr.ecr.eu-west-2.amazonaws.com/callisto/timecard-database:latest"
    volumes:
      - ./db/changelog:/liquibase/changelog
      - ./db/sql:/liquibase/sql

networks:
  callisto:
    name: callisto-localdev_callisto
    driver: bridge
    external: true