---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: clean-pods
  namespace: callisto-dev
  labels:
    app: clean-pods
spec:
  schedule: "* * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: runner
          restartPolicy: Never
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
          containers:
            - name: clean-pods
              imagePullPolicy: Always
              image: quay.io/ukhomeofficedigital/hocs-helm-kubectl:latest
              command:
                - /bin/sh
                - -c
                - helm uninstall callisto-timecard-restapi-eahw-2492