---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keystore-script
  labels:
    app: {{ .Release.Name }}
data:
  create-private-key.sh: |-
{{ .Files.Get "kafka/scripts/create-private-key.sh" | indent 4 }}
  aws-issue-certificate.sh: |-
{{ .Files.Get "kafka/scripts/aws-issue-certificate.sh" | indent 4 }}
  create-keystore.sh: |-
{{ .Files.Get "kafka/scripts/create-keystore.sh" | indent 4 }}