---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keystore-script
  labels:
    app: {{ .Release.Name }}
data:
  create-keystore.sh: |-
{{ .Files.Get "kafka/scripts/create-keystore.sh" | indent 4 }}