---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
  labels:
    app: {{ .Release.Name }}
data:
  create-keystore.sh: |-
{{ .Files.Get "kafka/scripts/create-keystore.sh" | indent 4 }}
  create-topic.sh: |-
{{ .Files.Get "kafka/scripts/create-topic.sh" | indent 4 }}
  kafka.sh: |-
{{ .Files.Get "kafka/scripts/kafka.sh" | indent 4}}
  permissions.txt: |-
{{ .Files.Get "kafka/scripts/permissions.txt" | indent 4 }}
  timecard-properties: |-
{{ .Files.Get "kafka/scripts/timecard-properties" | indent 4 }}