---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keystore-script
  labels:
    app: {{ .Release.Name }}
data:
  keystore-setup.sh: |-
  {{ .Files.Get "keystore-setup.sh" | indent 4}}

---
apiVersion: v1
kind: configMap
metadata:
  name: {{ .Release.Name }}-keystore-volume
  labels:
    app: {{ .Release.Name }}
data:
  copy-keystore.sh: |-
  {{ .Files.Get "copy-keystore.sh" | indent 4}}
