---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
        - name: timecard-restapi
          image: {{ .Values.image.repo }}timecard-restapi:{{ .Values.image.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1500m'
          ports:
            - name: http
              containerPort: 9090
          env: {{ toYaml .Values.env.database | nindent 12 }}
      initContainers:
        - name: timecard-database
          image: {{ .Values.image.repo }}timecard-database:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env: {{ toYaml .Values.env.database | nindent 12 }}
          args:
            - "--url=jdbc:postgresql://$(DATABASE_ENDPOINT):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - "--username=$(DATABASE_USERNAME)"
            - "--password=$(DATABASE_PASSWORD)"
            - "--changeLogFile=changelog/db.changelog-main.yml"
            - "--liquibaseSchemaName=timecard"
            - "update"
