---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  {{- if ne .Values.environment "prod" }}
  annotations:
    downscaler/uptime: Mon-Fri 08:00-20:00 Europe/London
  {{ end }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Release.Name }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 2000
      containers:
        - name: timecard-restapi
          image: {{ .Values.image.repo }}callisto-timecard-restapi:{{ .Values.image.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1500m'
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - mountPath: /timecard-restapi-keystore
              name: keystore-volume
            - name: timecard-restapi-script-volume
              mountPath: /scripts
          env: {{ toYaml .Values.env.database | nindent 12 }}
          {{- if .Values.env.kafka }}
            {{ toYaml .Values.env.kafka | nindent 12 }}
          {{ end }}
      initContainers:
        - name: timecard-database
          image: {{ .Values.image.repo }}callisto-timecard-database:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env: {{ toYaml .Values.env.database | nindent 12 }}
          args:
            - "--url=jdbc:postgresql://$(DATABASE_ENDPOINT):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - "--username=$(DATABASE_USERNAME)"
            - "--password=$(DATABASE_PASSWORD)"
            - "--changeLogFile=changelog/db.changelog-main.yml"
            - "--liquibaseSchemaName=timecard"
            - "update"
        {{- if eq .Values.environment "dev" }}
        - name: timecard-create-keystore
          image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/callisto/awscli-java-openssl:latest
          imagePullPolicy: Always
          env: {{ toYaml .Values.env.kafka | nindent 12 }}
          command: [ "/bin/sh" ]
          args: [ "/scripts/create-keystore.sh", "timecard-restapi", "/timecard-restapi-keystore" ,"$(AWS_CERTIFICATE_AUTHORITY_ARN)", "$(BOOTSTRAP_SERVER)", "$(TIMECARD_KEYSTORE_PASSWORD)", "$(AWS_ACCESS_KEY)", "$(AWS_SECRET_KEY)"]
          volumeMounts:
            - name: timecard-restapi-script-volume
              mountPath: /scripts/create-keystore.sh
              subPath: create-keystore.sh
            - name: keystore-volume
              mountPath: /timecard-restapi-keystore
        - name: timecard-create-topic
          image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/callisto/kafka
          imagePullPolicy: Always
          env: {{ toYaml .Values.env.kafka | nindent 12 }}
          command: [ "/bin/sh" ]
          args: [ "/scripts/kafka.sh", "timecard-restapi", "$(BOOTSTRAP_SERVER)", "/timecard-restapi-keystore", "$(TIMECARD_KEYSTORE_PASSWORD)", "callisto-timecard"]
          volumeMounts:
            - name: timecard-restapi-script-volume
              mountPath: /scripts
            - name: keystore-volume
              mountPath: /timecard-restapi-keystore
        {{ end }}
      volumes:
      - name: timecard-restapi-script-volume
        configMap:
            name: {{ .Release.Name }}-scripts
      - name: keystore-volume
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-volume-claim

