---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
        - name: timecard-restapi
          image: {{ .Values.image.repo }}/timecard-restapi:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1500m'
          ports:
            - name: http
              containerPort: 9090
      initContainers:
        - name: timecard-database
          image: {{ .Values.image.repo }}/timecard-database:latest
          env:
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: callistodev-rds
                  key: db_name
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: callistodev-rds
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: callistodev-rds
                  key: password
            - name: DATABASE_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: callistodev-rds
                  key: endpoint
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: callistodev-rds
                  key: port
          args:
            - "--url=jdbc:postgresql://$(DATABASE_ENDPOINT):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - "--username=$(DATABASE_USERNAME)"
            - "--password=$(DATABASE_PASSWORD)"
            - "--changeLogFile=changelog/db.changelog-main.yml"
            - "update"
