---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
        - name: timecard-restapi
          image: {{ .Values.image.repo }}timecard-restapi:{{ .Values.image.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1500m'
          ports:
            - name: http
              containerPort: 9090
          env: {{ toYaml .Values.env.database | nindent 12 }}
      initContainers:
        - name: timecard-database
          image: {{ .Values.image.repo }}timecard-database:{{ .Values.image.tag }}
          imagePullPolicy: Always
          env: {{ toYaml .Values.env.database | nindent 12 }}
          args:
            - "--url=jdbc:postgresql://$(DATABASE_ENDPOINT):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - "--username=$(DATABASE_USERNAME)"
            - "--password=$(DATABASE_PASSWORD)"
            - "--changeLogFile=changelog/db.changelog-main.yml"
            - "--liquibaseSchemaName=timecard"
            - "update
        - name: timecard-keystore
          image: quay.io/ukhomeofficedigital/dind-awscli
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["/scripts/create_keystore.sh"]
          volumeMounts:
            - name: keystore-script-volume
              mountPath: /scripts/create_keystore.sh
              subPath: create_keystore.sh
      volumes:
      - name: keystore-script-volume
        configMap:
            name: {{ .Release.Name }}-keystore-script
