---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    cert-manager.io/solver: route53
  annotations:
    cert-manager.io/enabled: "true"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: "nginx-internal"
    kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/enable-cors: "true"
    ingress.kubernetes.io/cors-allow-origin: "https://web.dev.callisto-notprod.homeoffice.gov.uk"
spec:
  tls:
    - hosts:
        - {{ .Values.image.tag }}-timecard.dev.callisto-notprod.homeoffice.gov.uk
      secretName: callisto-timecard-tls-{{ .Values.image.tag }}
  rules:
    - host: {{ .Values.image.tag }}-timecard.dev.callisto-notprod.homeoffice.gov.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.name }}
                port:
                  number: 9090