---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Egress
    - Ingress
