---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-network-policy-callisto-timecard
spec:
  podSelector:
    matchLabels:
      app: callisto-timecard-api
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Egress
    - Ingress
