---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-network-policy-{{ .Release.Name }}
  annotations:
    expiresIn: 3m
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  ingress:
    - {}
  egress:
    - {}
  policyTypes:
    - Egress
    - Ingress
