---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-network-policy-callisto-timecard
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  ingress:
    - {}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: callisto-timecard-tls-7c4n6-2hm4n-n5x4d
  policyTypes:
    - Egress
    - Ingress
