apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: callisto-timecard-volume-claim
  namespace: callisto-{{ .Values.environment }}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem