apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: callisto-timecard-volume-claim
  namespace: callisto-{{ .Values.environment }}
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi