apiVersion: v1
kind: PersistentVolume
metadata:
  name: callisto-keystore-volume
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    name: {{ .Release.Name }}-keystore-volume
    namespace: callisto-dev