apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: callisto-timecard-volume-claim
  namespace: callisto-{{ .Values.environment }}
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi