openapi: '3.0.3'
info:
  title: TimeCard
  description: The TimeCard container exposes a number of models to clients. The TimeEntry is a key model from which most others hang
  version: 0.1.0
paths: {}
components:
  schemas:
    DayNote:
      type: object
      description: A note is used to carry arbitrary textual information about a date. Notes are immutable.
      required: 
        - content
        - date
        - authorId
      properties:
        content:
          description: Holds the note's text
          type: string
        date:
           description: The date that the note is associated with
           type: string
           format: date   
           default: current date and time
        createdAt:
          description: Assigned by the TimeCard container when the note is persisted
          type: string
          format: date-time
        authorId:
            description: The id of the Person who wrote the note's content
            type: number  
    TimePeriodType:
      type: object
      description: A way to categorise time periods (e.g. a shift, a standard rest day). Depending on the type of time period the actual time value that should be recorded against that period varies. For example to record a shift time period two data points are needed - a shift start datetime and and a shift end datetime. Contrast this with a standard rest day where only a single date is needed. 
      required:
            - name
            - valueType
      properties:
        timePeriodTypeId: 
          description: the identifier for this TimePeriodType
          type: number
        name:
          description: the display name of this TimePeriodType
          type: string
        valueType:
          description: The value that a time period of this type should contain
          type: string
          enum: [date, datetime]
    TimeEntry:
      description: A TimeEntry carries the time periods during which employees have performed a business activity (e.g. PCP, dog handling etc) or HR activity (e.g. leaves, training etc). TimeEntry is the actual recording of hours done by employees as per their roster. Encapsulates day and time (to the minute). The TimeEntry also holds the concept of planned time. In this instance the owner of the TimeEntry has been rostered to perform some work in the future at a specified time. Not all TimeEntry owners are subject to their time being planned out therefore the fields related to planned time are optional. It is also possible to create a TimeEntry with just an actualStartTime and to provide the actualEndTime later. However if planned time is provided then both the start and end must be set.
      type: object
      required:
        - actualStartTime
        - timePeriodType
        - ownerId
      properties:
        timeEntryId:
          description: Assigned by the TimeCard container
          type: number
        version: 
          description: The version of the TimeEntry as assigned by the TimeCard container. This value changes when the resource is created, updated, or deleted.
          type: number
        ownerId:
            description: The id of the Person who owns this TimeEntry i.e. the Person who has performed the activity in the given time period
            type: number
        actualStartTime: 
          description: The start time of the activity that was worked (to the minute)
          type: string
          format: date-time
        actualEndTime: 
          description: The end time of the activity that was worked (to the minute)
          type: string
          format: date-time
        plannedStartTime: 
          description: The start time of the activity that has been planned (to the minute)
          type: string
          format: date-time
        plannedEndTime: 
          description: The end time of the activity that has been planned (to the minute)
          type: string
          format: date-time   
        shiftType:
          description: a descriptor for the shift (eg 'early shift')
          type: string
        timePeriodType:
            description: The type of time entry (e.g. a shift, a standard rest day)
            allOf:
              - $ref: '#/components/schemas/TimePeriodType'
    FlexChangeType:
      type: object
      description: The type of flexible change. The type drives business rules that govern how much notice the shift worker must have been given. In addition certain types of FlexChange cannot be combined on the same TimeEntry 
      required:
            - name
            - valueType
      properties:
        flexChangeTypeId: 
          description: the identifier for this FlexChangeType
          type: number
        name:
          description: the display name of this FlexChangeType
          type: string
    FlexChange:
      type: object
      description: A FlexChange is used to carry details of an alteration to a planned shift. For a FlexChange to be created there are business rules governing how far in advance of the shift the alteration was made
      required: 
        - flexChangeType
        - authorisedBy
        - authorId
        - timeEntryId
        - timeEntryVersion
      properties:
        flexChangeType:
          description: Holds the note's text
          $ref: '#/components/schemas/FlexChangeType'
        authorisedBy:
          description: free text field holding the name of the person who authorised the creation of the flexible change. Authorisation is handled outside of Callisto
          type: string
        note:
           description: hold arbitrary information about the flexible change
           type: string
        createdAt:
          description: Assigned by the TimeCard container when the FlexChange is persisted
          type: string
          format: date-time
        authorId:
            description: The id of the Person who created the FlexChange
            type: number 
        timeEntryId:
            description: The id of the TimeEntry associated with the FlexChange
            type: number  
        timeEntryVersion:
            description: The version of the TimeEntry associated with the FlexChange
            type: number              
