image:
  repository: quay.io/ukhomeofficedigital/callisto-timecard-restapi
  tag: latest
  pullPolicy: Always

service:
  port: 9090

deploymentAnnotations:
  downscaler/uptime: Mon-Fri 08:00-20:00 Europe/London

kafka:
  defaultTopic: callisto-timecard-timeentries
  createTopics:
    - callisto-timecard-timeentries
  indentity: timecard-restapi
  permissions: |-    
    # Timecard prefix permissions
    --topic timecard --resource-pattern-type prefixed
    User:timecard-restapi     Write       Allow
    User:timecard-restapi     Describe    Allow
  mskSecretKeyRefName: callisto-dev-msk
  bootstrapSecretKeyRefName: callisto-dev-bootstrap

resources:
  requests:
    memory: '512Mi'
    cpu: '500m'
  limits:
    memory: '1Gi'


