environment: prod
branch: main

service:
  port: 3000

replicaCount: 1

image:
  repo: quay.io/ukhomeofficedigital/
  tag: latest # this value will be overridden by drone.yml

env:
  database:
    - name: DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: callisto-prod-1
          key: db_name
    - name: DATABASE_USERNAME
      valueFrom:
        secretKeyRef:
          name: callisto-prod-1
          key: username
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: callisto-prod-1
          key: password
    - name: DATABASE_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: callisto-prod-1
          key: endpoint
    - name: DATABASE_PORT
      valueFrom:
        secretKeyRef:
          name: callisto-prod-1
          key: port
  kafka:
    - name: BOOTSTRAP_SERVER
      valueFrom:
        secretKeyRef:
          name: callisto-prod-bootstrap
          key: bootstrap_server1
    - name: AWS_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: callisto-prod-msk
          key: certificate_authority_access_keys
    - name: AWS_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: callisto-prod-msk
          key: certificate_authority_secret_keys
    - name: AWS_CERTIFICATE_AUTHORITY_ARN
      valueFrom:
        secretKeyRef:
          name: callisto-prod-msk
          key: certificate_authority_arn
    - name: TIMECARD_KEYSTORE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: callisto-prod-timecard-keystore
          key: password
    - name: TIMECARD_TOPIC
      value: callisto-timecard-timeentries