name: callisto-timecard-restapi

service:
  name: callisto-timecard-restapi
  port: 3000

replicaCount: 1

image:
  repo: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/callisto/
  tag: latest # this value will be overridden by drone.yml

env:
  database:
    - name: DATABASE_NAME
      valueFrom:
        secretKeyRef:
          name: callisto-test-aurora
          key: db_name
    - name: DATABASE_USERNAME
      valueFrom:
        secretKeyRef:
          name: callisto-test-aurora
          key: username
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: callisto-test-aurora
          key: password
    - name: DATABASE_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: callisto-test-aurora
          key: endpoint
    - name: DATABASE_PORT
      valueFrom:
        secretKeyRef:
          name: callisto-test-aurora
          key: port