openapi: '3.0.3'
info:
  title: TimeCard
  description: The TimeCard container exposes a number of models to clients. The TimeEntry is a key model from which most others hang
  version: 0.1.0
paths: {}
components:
  schemas:
    Note:
      type: object
      description: A note is used to carry arbirtiary textual information about a TimeEntry. Notes are immutable and cannot exist without an associated TimeEntry.
      required: 
        - content
      properties:
        content:
          description: Holds the note's text
          type: string
        created_at:
          description: Assiged by the TimeCard container when the note is persisted
          type: string
          format: date-time
    CodedValue:
      type: object
      description: A CodeValue encapsulates a code
      required:
        - code
      properties:
        code:
          description: The code itself
          type: string
        namespace:
          description: The optional namespace that the code belongs to. The namespace and code together present a unique identifier for the CodedValue in the context of the TimeCard container
          type: string
          format: uri
          default: http://[tenantId].timecard.sas.digital.homeoffice.go.uk
        display:
          description: The optional human-readable label for the code
          type: string
          default: the value of the code property
    TimeEntry:
      description: A TimeEntry carries the time periods during which employees have performed a business activity (e.g. PCP, dog handling etc) or HR activity (e.g. leaves, training etc). TimeEntry is the actual recording of hours done by employees as per their roster. Encapsulates day and time (to the minute).
      type: object
      required:
        - actualStartTime
        - actualEndTime
        - timePeriodType
        - activity
      properties:
        id:
          description: Assigned by the TimeCard container
          type: number
        version: 
          description: The version of the TimeEntry as assifned by the TimeCard container. This value changes when the resource is created, updated, or deleted.
          type: number
        actualStartTime: 
          description: The start time of the acvitiy that was worked (to the minute)
          type: string
          format: date-time
        actualEndTime: 
          description: The end time of the acvitiy that was worked (to the minute)
          type: string
          format: date-time
        timePeriodType:
            description: The type of time entry (e.g. a shift, a standard rest day)
            allOf:
              - $ref: '#/components/schemas/CodedValue'
        activity:
            description: The type of work that has been carried out (e.g PCP)
            allOf:
              - $ref: '#/components/schemas/CodedValue'
        notes:
          description: The set of Notes that have been recorded against this TimeEntry
          type: array
          items: 
            $ref: '#/components/schemas/Note'